service:
  name: cart
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/cart"
  tag: "7cec427a6dff62a645c40ebe33b433651e2262ea"
  digest: "sha256:9acc77533e09aaf8be13e996482c7b32e26921546a840cebea5a19fc64ff4ba3"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
