service:
  name: checkout
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/checkout"
  tag: "0392223a4f44e97deddc2b588a37586b8688f327"
  digest: "sha256:5a0dbe4642b96c4eb7967cd911cd2e2d35e9aefd121e27c241d2e86dcb875294"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false
