service:
  name: currency
  environment: dev
  port: 7001
  targetPort: 7001

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/currency"
  tag: "7cec427a6dff62a645c40ebe33b433651e2262ea"
  digest: "sha256:ad5769b9753fd82d0254434447188b8a1b7a08a27eb78bcd9529a0fd14e6fea9"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: CURRENCY_PORT
    value: "7001"
