service:
  name: currency
  environment: dev
  port: 7001
  targetPort: 7001

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/currency"
  tag: "ad311d672caa4401e5a3a7dc082729491772f66b"
  digest: "sha256:feabcaa50a12eb45af26b6cbd39bf58b88f78d94342b72489bd7241710b4ce28"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: CURRENCY_PORT
    value: "7001"
