service:
  name: email
  environment: dev
  port: 8080
  targetPort: 8080

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/email"
  tag: "8ca520da1e5b850ef3243cb00c267c7814ac8266"
  digest: "sha256:61e9cde5407b5e1214a9e8cd7f9bd1c0c4402d1a9b3dfa1cafe188034e6a4137"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 1
  maxSurge: 0

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: EMAIL_PORT
    value: "8080"
