service:
  name: frontend
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/frontend"
  tag: "63f4d42f23ad9d999f676799cc5f3f5e102478c1"
  digest: "sha256:b70b09e04538c16753346a4e147031bc9b5a7ea053b2aafbebebff026196e079"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 1
  maxSurge: 0

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: CART_ADDR
    value: "cart:8080"
  - name: CHECKOUT_ADDR
    value: "checkout:5050"
  - name: CURRENCY_ADDR
    value: "currency:7001"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
  - name: RECOMMENDATION_ADDR
    value: "recommendation:1010"
