service:
  name: frontend
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/frontend"
  tag: "f87dd34107348267556674e2fa688d4c63b77023"
  digest: "sha256:4a837021c531b6a8aa4b9ab93a3726408581de65ce49a523599141927157eef8"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 1
  maxSurge: 0

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: CART_ADDR
    value: "cart:8080"
  - name: CHECKOUT_ADDR
    value: "checkout:5050"
  - name: CURRENCY_ADDR
    value: "currency:7001"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
  - name: RECOMMENDATION_ADDR
    value: "recommendation:1010"
  - name: SHIPPING_ADDR
    value: "shipping:50051"
