service:
  name: frontend
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/frontend"
  tag: "ed4f7762fd5381debc95f5e676f468c421eb664c"
  digest: "sha256:53d7b51aa8ab41cd4a92251b3740ed82c3e297ac95007291b729be7196ad5452"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 1
  maxSurge: 0

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false
