service:
  name: image-provider
  environment: dev
  port: 8081
  targetPort: 8081

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/image-provider"
  tag: "767946e9e4d1631600ccdd7f0a48236ec310aed8"
  digest: "sha256:aa9c9589de723eb46798a2b36241ad37e9b814f2b70fd7da7f7f3851205b35d3"
  pullPolicy: IfNotPresent

replicaCount: 1

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: IMAGE_PROVIDER_PORT
    value: "8081"
  - name: OTEL_SERVICE_NAME
    value: "image-provider"
  - name: OTEL_COLLECTOR_HOST
    value: "otel-collector"
  - name: OTEL_COLLECTOR_PORT_GRPC
    value: "4317"

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
