service:
  name: image-provider
  environment: dev
  port: 8081
  targetPort: 8081

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/image-provider"
  tag: "2656024e456816ae077c9a2190363853a5ef8b63"
  digest: "sha256:5367c0140bbe78c60241985f380d0fe639700e996108ad2d49384a604cac6950"
  pullPolicy: IfNotPresent

replicaCount: 1

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: IMAGE_PROVIDER_PORT
    value: "8081"
  - name: OTEL_SERVICE_NAME
    value: "image-provider"
  - name: OTEL_COLLECTOR_HOST
    value: "opentelemetry-collector.observability.svc.cluster.local"
  - name: OTEL_COLLECTOR_PORT_GRPC
    value: "4317"

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
