service:
  name: image-provider
  environment: dev
  port: 8081
  targetPort: 8081

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/image-provider"
  tag: "e1acb3a2a76504e7b42cd3c3721fdde9caf83e22"
  digest: "sha256:c239f22511eb21d29d361b57f1605529e927adfeb8cba044512b5d81b13464a9"
  pullPolicy: IfNotPresent

replicaCount: 1

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: IMAGE_PROVIDER_PORT
    value: "8081"

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
