service:
  name: payment
  environment: dev

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/payment"
  tag: "b6b9f6fac4a02b991b696e01fbc38c0eeb1fa53c"
  digest: "sha256:f57d53e63e98fe38c28d9645f8504bf9f485d5d3e42cba47901ff28a356549e4"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false
