service:
  name: recommendation
  environment: dev
  port: 1010
  targetPort: 1010

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "64d69032dbb768eff796fd85dc0ceab5db3773c2"
  digest: "sha256:958effb712a310a308cdd0824ebaa2eb3603f91e021817edd7b74fb1c410d1ef"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: OTEL_SERVICE_NAME
    value: "recommendation"
  - name: RECOMMENDATION_PORT
    value: "1010"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
