service:
  name: recommendation
  environment: dev
  port: 1010
  targetPort: 1010

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "794393e2bee04414a0b8839a9e60b2205026d46a"
  digest: "sha256:a0f4641c8ce6815eee7ea5018ad3b82a3820627d228a8f18eca2b37926647eeb"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: OTEL_SERVICE_NAME
    value: "recommendation"
  - name: RECOMMENDATION_PORT
    value: "1010"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
