service:
  name: recommendation
  environment: dev
  port: 1010
  targetPort: 1010

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "50cc97d272409c30cfd2e9b670e97979bf5ae054"
  digest: "sha256:d6f23fe27ff02517861e5a007d3f58434c23eef99dcdd1593bd92f22626517bd"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 0
  maxSurge: 1

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: OTEL_SERVICE_NAME
    value: "recommendation"
  - name: RECOMMENDATION_PORT
    value: "1010"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
