service:
  name: shipping
  environment: dev
  port: 50051
  targetPort: 50051

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/shipping"
  tag: "472a04063c30ddf9bdcc3018eaee2c6157884239"
  digest: "sha256:b357da069f6064bbce59fe836b2e78f7ffea21c46105a9e9025b63a81663582d"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

rollout:
  strategy: canary
  maxUnavailable: 1
  maxSurge: 0

observability:
  metrics:
    enabled: false
  tracing:
    enabled: false

istio:
  enabled: false

env:
  - name: SHIPPING_PORT
    value: "50051"
