apiVersion: v1
kind: Service
metadata:
  name: {{ include "astronomy-shop-service.fullname" . }}
  labels:
    {{- include "astronomy-shop-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "astronomy-shop-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName | default "http" }}
{{- if not .Values.rollout.trafficRouting.istio.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-stable" (include "astronomy-shop-service.fullname" .) }}
  labels:
    {{- include "astronomy-shop-service.labels" . | nindent 4 }}
    rollouts.argoproj.io/service-role: stable
spec:
  type: ClusterIP
  selector:
    {{- include "astronomy-shop-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName | default "http" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-canary" (include "astronomy-shop-service.fullname" .) }}
  labels:
    {{- include "astronomy-shop-service.labels" . | nindent 4 }}
    rollouts.argoproj.io/service-role: canary
spec:
  type: ClusterIP
  selector:
    {{- include "astronomy-shop-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName | default "http" }}
{{- end }}
