apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: astronomy-shop-dev-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - list:
        elements:
          - service: frontend-proxy
          - service: frontend
          - service: recommendation
          - service: cart
          - service: checkout
          - service: product-catalog
          - service: payment
          - service: currency
          - service: image-provider
  template:
    metadata:
      name: "{{service}}-dev"
      labels:
        app.kubernetes.io/part-of: astronomy-shop
        service: "{{service}}"
        environment: dev
    spec:
      project: dev
      source:
        repoURL: git@github.com:cloudnative-platform-lab/astronomy-shop-gitops.git
        targetRevision: main
        path: charts/astronomy-shop-service
        helm:
          valueFiles:
            - ../../helm-values/dev/{{service}}-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: argoproj.io
          kind: Rollout
          jsonPointers:
            - /spec/replicas
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
