service:
  name: frontend
  environment: prod

image:
  repository: ""
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent

replicaCount: 4

resources:
  requests:
    cpu: 400m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

rollout:
  strategy: canary
  steps:
    - setWeight: 10
    - pause:
        duration: 10m
    - setWeight: 25
    - pause:
        duration: 15m
    - setWeight: 50
    - pause:
        duration: 15m
    - setWeight: 100

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false

env:
  - name: CART_ADDR
    value: "cart:8080"
  - name: CHECKOUT_ADDR
    value: "checkout:5050"
  - name: CURRENCY_ADDR
    value: "currency:7001"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
  - name: RECOMMENDATION_ADDR
    value: "recommendation:1010"
