service:
  name: cart
  environment: staging

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/cart"
  tag: "69e9bf247c45cad3c266d86ee8c458435f8e0350"
  digest: "sha256:f823d239f4f33c41d177e2b6371b0bceb304157691411bdaa320fd208fc3b36d"
  pullPolicy: IfNotPresent

replicaCount: 2

podAnnotations:
  astronomy-shop.io/canary-analysis-retry: "v2"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: false
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100
  analysis:
    enabled: true

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false
  trafficRouting:
    enabled: false
  mtls:
    enabled: false
  authorizationPolicy:
    enabled: false

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
