service:
  name: cart
  environment: staging

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/cart"
  tag: "88abe4e9c1e3c3e9849d14b5e9601d72bf872fd4"
  digest: "sha256:ef5dee3372341fe78833cfbf716c59efe621a1a34d907fd82782ca573cbf0792"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: false
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100
  analysis:
    enabled: true

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false
  trafficRouting:
    enabled: false
  mtls:
    enabled: false
  authorizationPolicy:
    enabled: false

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
