service:
  name: frontend
  environment: staging

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/frontend"
  tag: "693be061762a1f601b7463f2e8b955f47df97705"
  digest: "sha256:acec54e827b7d7ce00abffa7b5529a2dc1e0200f925f6209b4da7c2f0a4e85de"
  pullPolicy: IfNotPresent

replicaCount: 2

podAnnotations:
  sidecar.istio.io/inject: "true"
  platform.astronomy-shop/mesh-validation: "recommendation-caller"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 700m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: true

env:
  - name: CART_ADDR
    value: "cart:8080"
  - name: CHECKOUT_ADDR
    value: "checkout:5050"
  - name: CURRENCY_ADDR
    value: "currency:7001"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
  - name: RECOMMENDATION_ADDR
    value: "recommendation:1010"
  - name: EXPOSE_RECOMMENDATION_REVISION_HEADERS
    value: "true"
