service:
  name: image-provider
  environment: staging
  port: 8081
  targetPort: 8081

image:
  repository: ""
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent

replicaCount: 2

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: true
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: true
  trafficRouting:
    enabled: true
  mtls:
    enabled: true
  authorizationPolicy:
    enabled: true

env:
  - name: IMAGE_PROVIDER_PORT
    value: "8081"
  - name: OTEL_SERVICE_NAME
    value: "image-provider"
  - name: OTEL_COLLECTOR_HOST
    value: "otel-collector"
  - name: OTEL_COLLECTOR_PORT_GRPC
    value: "4317"

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
