service:
  name: image-provider
  environment: staging
  port: 8081
  targetPort: 8081

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/image-provider"
  tag: "2656024e456816ae077c9a2190363853a5ef8b63"
  digest: "sha256:5367c0140bbe78c60241985f380d0fe639700e996108ad2d49384a604cac6950"
  pullPolicy: IfNotPresent

replicaCount: 2

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: false
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false
  trafficRouting:
    enabled: false
  mtls:
    enabled: false
  authorizationPolicy:
    enabled: false

env:
  - name: IMAGE_PROVIDER_PORT
    value: "8081"
  - name: OTEL_COLLECTOR_HOST
    value: "otel-collector"
  - name: OTEL_COLLECTOR_PORT_GRPC
    value: "4317"

envFrom:
  - secretRef:
      name: astronomy-shop-runtime
      optional: false
