service:
  name: product-catalog
  environment: staging
  port: 3550
  targetPort: 3550

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/product-catalog"
  tag: "ad311d672caa4401e5a3a7dc082729491772f66b"
  digest: "sha256:dfee7f628cec94982530a9267b9c0a568c3d17846d2d5c4d24531a8517085d3f"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: false
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false
  trafficRouting:
    enabled: false
  mtls:
    enabled: false
  authorizationPolicy:
    enabled: false

env:
  - name: PRODUCT_CATALOG_PORT
    value: "3550"
