service:
  name: recommendation
  environment: staging
  port: 1010
  portName: grpc
  targetPort: 1010

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "e79b2599f54390b1d22d0de571486d6ef29f65b3"
  digest: "sha256:298822bcf7f1f5be83d74fb40ab8723f169a157f797bb8a0b11442db2c2aacf4"
  pullPolicy: IfNotPresent

replicaCount: 2

podAnnotations:
  sidecar.istio.io/inject: "true"
  platform.astronomy-shop/mesh-validation: "staging-routing-validation-v2"
  astronomy-shop.io/canary-validation: "routing-disabled-after-failed-validation"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: false
  steps:
    - setWeight: 100
  analysis:
    enabled: false

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: true
  trafficRouting:
    enabled: false
  mtls:
    enabled: false
  authorizationPolicy:
    enabled: false

env:
  - name: FEATURE_FLAGS_ENABLED
    value: "false"
  - name: ASTRONOMY_SHOP_SERVING_REVISION
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['rollouts-pod-template-hash']
  - name: RECOMMENDATION_PORT
    value: "1010"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
