service:
  name: recommendation
  environment: staging
  port: 1010
  portName: grpc
  targetPort: 1010

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "50cc97d272409c30cfd2e9b670e97979bf5ae054"
  digest: "sha256:d6f23fe27ff02517861e5a007d3f58434c23eef99dcdd1593bd92f22626517bd"
  pullPolicy: IfNotPresent

replicaCount: 2

podAnnotations:
  sidecar.istio.io/inject: "true"
  platform.astronomy-shop/mesh-validation: "staging-routing-validation-v2"
  astronomy-shop.io/canary-validation: "v2"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: true
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100
  analysis:
    enabled: true

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: true
  trafficRouting:
    enabled: true
  mtls:
    enabled: false
  authorizationPolicy:
    enabled: false

env:
  - name: ASTRONOMY_SHOP_SERVING_REVISION
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['rollouts-pod-template-hash']
  - name: RECOMMENDATION_PORT
    value: "1010"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
