service:
  name: recommendation
  environment: staging
  port: 1010
  targetPort: 1010

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/recommendation"
  tag: "ad311d672caa4401e5a3a7dc082729491772f66b"
  digest: "sha256:f881befd94fade54541a556241bf9b2fb5f1b8cfd1468d798010ad0e52b9cc56"
  pullPolicy: IfNotPresent

replicaCount: 2

podAnnotations:
  sidecar.istio.io/inject: "true"
  platform.astronomy-shop/mesh-validation: "enabled"

podAnnotations:
  sidecar.istio.io/inject: "true"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary
  trafficRouting:
    istio:
      enabled: false
  steps:
    - setWeight: 25
    - pause:
        duration: 5m
    - setWeight: 50
    - pause:
        duration: 10m
    - setWeight: 100

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false
  trafficRouting:
    enabled: false
  mtls:
    enabled: false
  authorizationPolicy:
    enabled: false

env:
  - name: RECOMMENDATION_PORT
    value: "1010"
  - name: PRODUCT_CATALOG_ADDR
    value: "product-catalog:3550"
