service:
  name: shipping
  environment: staging
  port: 50051
  targetPort: 50051

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/shipping"
  tag: "0f85fbcee0e4a63291dfa68f028f4421ba1c529e"
  digest: "sha256:72ba676ef412fd3b89d006d02e819b1a1d4f53d7208c9c014fbd687d1e59ba61"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false

env:
  - name: SHIPPING_PORT
    value: "50051"
