service:
  name: shipping
  environment: staging
  port: 50051
  targetPort: 50051

image:
  repository: "241766333730.dkr.ecr.ap-south-1.amazonaws.com/astronomy-shop/shipping"
  tag: "69e9bf247c45cad3c266d86ee8c458435f8e0350"
  digest: "sha256:1ddddc93e279f0989a74baaa49fb15c327770cd1ac0694f054f183f5ec135871"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

rollout:
  strategy: canary

observability:
  metrics:
    enabled: true
  tracing:
    enabled: true

istio:
  enabled: false

env:
  - name: SHIPPING_PORT
    value: "50051"
